name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true
  types:
    description: override the default types
    required: false
    default: |
      type1
      type2
      type3
      type4
  scopes:
    description: override scopes
    required: false
    default: |
      one
      two
      three

runs:
  using: composite
  steps:
    - uses: actions/github-script@v6
      with:
        script: |
          const fs = require("fs")
          const process = require("process")
          const cwd = process.cwd()
          console.log(cwd)
          console.log("cwd")
          console.log(fs.readdirSync(cwd))
          console.log("..")
          console.log(fs.readdirSync(".."))
          return { a: 1, b: 2 }
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ inputs.types }}
        scopes: ${{ inputs.scopes }}
