name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true

runs:
  using: composite
  steps:
    - id: types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const defaultTypes = `
            feat
            fix
            revert
            docs
            style
            refactor
            test
            build
            autogen
            security
            ci
            chore`
          const configPath = ".github/conventional_commits.json"
          try {
            var configText = require("fs").readFileSync(configPath, "utf8")
          } catch (e) {
            return defaultTypes
          }
          try {
            var config = JSON.parse(configText)
          } catch (e) {
            console.log(`ERROR: invalid JSON in ${configPath}:`, e)
            return defaultTypes
          }
          const types = config.types ? config.types.join("\n") : defaultTypes
          return config.addTypes ? types + "\n" + config.addTypes.join("\n") : types

    - id: scopes
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const defaultScopes = `
            blog
            cms
            deps
            docs
            home
            stats`
          const configPath = ".github/conventional_commits.json"
          try {
            var configText = require("fs").readFileSync(configPath, "utf8")
          } catch (e) {
            return defaultScopes
          }
          try {
            var config = JSON.parse(configText)
          } catch (e) {
            console.log(`ERROR: invalid JSON in ${configPath}:`, e)
            return defaultScopes
          }
          let scopes = config.scopes ? config.scopes.join("\n") : defaultScopes
          return config.addScopes ? scopes + "\n" + config.addScopes.join("\n") : scopes

    - id: require_scope
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const configPath = ".github/conventional_commits.json"
          try {
            var configText = require("fs").readFileSync(configPath, "utf8")
          } catch (e) {
            return false
          }
          try {
            var config = JSON.parse(configText)
          } catch (e) {
            console.log(`ERROR: invalid JSON in ${configPath}:`)
            console.log(e)
            return false
          }
          return config.requireScope ? config.requireScope : false

    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ steps.types.outputs.result }}
        scopes: ${{ steps.scopes.outputs.result }}
        requireScope: ${{ steps.require_scope.outputs.result }}
        subjectPatternError: |
          The subject should start with a lowercase letter, yours is uppercase:
          "{subject}"
