name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true

runs:
  using: composite
  steps:
    - id: config
      uses: actions/github-script@v6
      with:
        script: |
          const CONFIG_PATH = ".github/conventional_commits.json"
          try {
            var configText = require("fs").readFileSync(CONFIG_PATH, "utf8")
          } catch (e) {
            return {}
          }
          try {
            return JSON.parse(configText)
          } catch (e) {
            console.log(`ERROR: invalid JSON in ${CONFIG_PATH}:`, e)
          }
          return {}

    - id: types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const DEFAULT_TYPES = `
            feat
            fix
            revert
            docs
            style
            refactor
            test
            build
            autogen
            security
            ci
            chore
          `
          const config = ${{ steps.config.outputs.result }}
          const types = config.types ? config.types.join("\n") : DEFAULT_TYPES
          return config.addTypes ? types + "\n" + config.addTypes.join("\n") : types

    - id: scopes
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const DEFAULT_SCOPES = `
            blog
            cms
            deps
            docs
            home
            stats
          `
          const config = ${{ steps.config.outputs.result }}
          let scopes = config.scopes ? config.scopes.join("\n") : DEFAULT_SCOPES
          return config.addScopes ? scopes + "\n" + config.addScopes.join("\n") : scopes

    - id: require_scope
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const config = ${{ steps.config.outputs.result }}
          return config.requireScope ? config.requireScope : false

    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ steps.types.outputs.result }}
        scopes: ${{ steps.scopes.outputs.result }}
        requireScope: ${{ steps.require_scope.outputs.result }}
        subjectPatternError: |
          The subject should start with a lowercase letter, yours is uppercase:
          "{subject}"
