name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true

runs:
  using: composite
  steps:
    - name: define the default types
      id: default_types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const defaultTypes = `
            feat
            fix
            revert
            docs
            style
            refactor
            test
            build
            autogen
            security
            ci
            chore
          `
          return defaultTypes.trim()
    - name: customize types based on config file
      id: custom_types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          let types = `${{ steps.default_types.outputs.result }}`
          const fs = require("fs")
          const configPath = ".github/conventional_commits.json"
          try {
            var configText = fs.readFileSync(configPath, "utf8")
          } catch (e) {
            // no config file found --> use the default types
            return types
          }
          try {
            var config = JSON.parse(configText)
          } catch (e) {
            console.log(`ERROR: invalid JSON in ${configPath}:`)
            console.log(e)
            return types
          }
          console.log(config)
          console.log(config.types)
          if (config.types) {
            types = config.types.join("\n")
          }
          if (config.addTypes) {
            types += "\n" + config.addTypes.join("\n")
          }
          console.log("types at end:", types)
          return types
    - run: echo "${{steps.custom_types.outputs.result}}"
      shell: bash
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ steps.custom_types.outputs.result }}
        # scopes: ${{ inputs.scopes }}
