name: conventional
description: test

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true
  scopes:
    description: override scopes
    required: false
    default: one, two, three

runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
