name: conventional
description: test

inputs:
  GITHUB_TOKEN:
    description: GitHub token
    required: true

runs:
  using: composite
  steps:
    - run: echo 111111111111111
      shell: bash
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
    - run: echo 222222222222222
      shell: bash
