name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

outputs:
  types:
    description: the default types
    value: |
      type1
      type2
      type3
inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true
  scopes:
    description: override scopes
    required: false
    default: |
      one
      two
      three

runs:
  using: composite
  steps:
    - id: customize_types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const fs = require("fs")
          const types = `${{ outputs.types }}`
          try {
            const config = fs.readFileSync(".github/conventional_commits.json", "utf8")
          } catch (e) {
            // no config file found --> use the default types
            return types
          }
          console.log(config)
          if (config.types) {
            types = config.types
          }
          if (config.addTypes) {
            types += config.addTypes
          }
          return types
    - run: echo "${{steps.load_types.outputs.result}}"
      shell: bash
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ inputs.types }}
        scopes: ${{ inputs.scopes }}
