name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  types:
    description: override the default types
    required: false
    default: |
      type1
      type2
      type3
      type4
  scopes:
    description: override scopes
    required: false
    default: |
      one
      two
      three

runs:
  using: composite
  steps:
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: $GITHUB_TOKEN
      with:
        types: ${{ inputs.types }}
        scopes: ${{ inputs.scopes }}
