name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true
  types:
    description: override the default types
    required: false
    default: |
      type1
      type2
      type3
      type4
  scopes:
    description: override scopes
    required: false
    default: |
      one
      two
      three

runs:
  using: composite
  steps:
    - id: load
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require("fs")
          const defaultTypes = "${{ inputs.types }}"
          console.log(defaultTypes)
          console.log(fs.readdirSync("."))
          const content = fs.readFileSync("README.md", "utf8")
          console.log(content)
          return { a: 1, b: 2 }
    - run: echo "${{steps.load.outputs.result}}"
      shell: bash
    - run: echo "${{steps.load.outputs.result.a}}"
      shell: bash
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ inputs.types }}
        scopes: ${{ inputs.scopes }}
