name: conventional commits
description:
  enforces conventional commit style in pull requests with Ory-specific defaults

inputs:
  GITHUB_TOKEN:
    description: the GitHub token to use
    required: true

runs:
  using: composite
  steps:
    - name: define the default types
      id: default_types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const defaultTypes = [
            "type1",
            "type2",
            "type3"
          ]
          return defaultTypes.join("\n")
    - name: customize types based on config file
      id: custom_types
      uses: actions/github-script@v6
      with:
        result-encoding: string
        script: |
          const types = `${{ steps.default_types.outputs.result }}`
          const fs = require("fs")
          try {
            const config = fs.readFileSync(".github/conventional_commits.json", "utf8")
          } catch (e) {
            // no config file found --> use the default types
            return types
          }
          console.log(config)
          if (config.types) {
            types = config.types
          }
          if (config.addTypes) {
            types += config.addTypes
          }
          return types
    - run: echo "${{steps.custom_types.outputs.result}}"
      shell: bash
    - uses: amannn/action-semantic-pull-request@v4
      env:
        GITHUB_TOKEN: ${{ inputs.GITHUB_TOKEN }}
      with:
        types: ${{ steps.custom_types.outputs.result }}
        # scopes: ${{ inputs.scopes }}
