name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: README.md
          key: ${{ runner.os }}-test
      - run: pwd
      - run: cd .. && pwd && ls -la
      - run: cd ../.. && pwd && ls -la
      - run: cd ../../_actions && pwd && ls -la
